services:
    test_db:
        container_name: test_database_db
        image: postgres:16
        environment:
            POSTGRES_DB: cxx_client
            POSTGRES_USER: cxx_client
            POSTGRES_PASSWORD: cxx_client
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "cxx_client"]
            timeout: 5s
            interval: 30s
            retries: 3
        ports:
            - "5556:5432"

